---
title: Presentation
format:
  pdf:
    fontfamily: helvet
    fontsize: 18pt
    papersize: a4
---

# Slide 1

Committee members, colleagues, friends and family,

I would like to thank you all for attending my presentation here today. I will
be defending my thesis with title "Beyond the average treatment effect:
Risk-based approaches to medical decision making".

\newpage

# Slide 2

Since we are looking at "risk-based" approaches it is important that I start
this talk from the elaborating on risk and its prediction.

The notion of prediction is present in everyone's life, especially whenever a
decision has to be made. For example, I leave around 50 kilometers away from
hospital in Rotterdam and I have to use some roads with quite heavy traffic. So,
every day I need to decide: "What time should I leave home for work to be there
on time?". To make this decsion I need to predict: "How much time will it take
me to drive to work"? From my experience, this depends on many factors. For
example, what day is it?  Is it Tuesday or Thursday? These days, trafffic seems
to be way worse than other days. What time is it? Is it rush hour?  What's the
weather like? Is it raining? Probably it's raining, but you know what I mean.

\newpage

# Slide 3

Now, decisions in healthcare are also very important. A question that is very
often asked is: "for a specific patient, how likely is it that they experience
an outcome of interest"?

For example, for a patient with hypertension, how likely is that they experience
an heart attack? Or, for a patient with covid-19, how likely is
it that they are admitted to the intensive care unit?

In this case, as making the right decision is crucial and the consequences of a
wrong decision can be severe, we need to use a more elaborate approach for our
predictions. This process, which can often be quite complex, is called
prediction modeling and its aim is to develop a clearly defined rule that
relates an outcome to patient characteristics that were known to us at the
moment the decision needed to be made. It attempts to define a more systematic
way for evaluating the likelihood of future outcomes using the experience from
past.

\newpage

# Slide 4

For example, in chapter 6 of my thesis we developed a model for the prediction
of a patient's likelihood of dying or being admitted to the ICU within 28 days
from being admitted to hospital with suspected covid-19. We also developed an
online calculator to be used by clinicians that looked like the one in this
picture, where the doctors could input some of the patient's measurements at the
time of admission and it would return their probabilities of dying or needing
intensive care treatment.

\newpage

# Slide 5

Now, all this is definitely helpful if you want to know which patient you should
be paying closer attention to. However, a physician, needs to be able to propose
a course of treatment for the patient sitting in front them. This means that,
very often, the question a doctor needs to answer is: "For a specific patient,
is treatment A better or treatment B"?

However, when we attempt to develop a model for this prediction problem the same
way we have presented so far, we run into a problem. In the case of covid-19 and
admission to the ICU, we know for every patient in our data whether they
actually ended up in the ICU or not. This allows us to explore the relationship
of the ICU admission with certain patient characteristics. However, that is not
the case when we are comparing treatments.

\newpage

# Slide 6

We can never observe what would have happened, had the patient received the
alternative treatment. The moment the patient receives treatment A, it is
impossible for us to observe their outcome with treatment B. Therefore, we
cannot know if the the decision to give the patient treatment A was the correct
one.

But what would then be the appropriate approach for predicting the patient's
benefit with treatment A compared to treatment B?

\newpage

# Slide 7

Let's follow a thought process starting from science fiction and ending to what
is really done in practice. Let's say we wanted to define a model for the
prediction of benefit with treatment A compared to treatment B. And we want to
develop this model on a large set of patients we have recruited.

Ideally, in order to observe the patient's response to both treatments we would
first need to give them treatment A, follow them for a specific amount of time
and record what happened to them. Then, put them in a time machine, send them
back in time to the moment of the decision, but now give them treatment B,
instead. Follow them up for the same amount of time and record their
response. At this point we would have the outcomes for both treatment decisions
and we could say with certainty that treatment A or B was better for this
patient. Then, we would do the same thing for all the patients we had recruited
and now our data would be complete. We could finally build a model that relates
the observed responses of our patients to their characteristics. And then, we
could use this model on any new patient that we would come across to decide
whether to give them treatment A or treatment B. Even though, I don't know how
useful such a model would be, given that you have a time machine available,
anyway.

Since time travel is not an option, we could say that next best thing would be
to clone the patient, give each person a different treatment, follow them up for
a period of time, and then see which version of the patient did better.

Even though, this is not permitted, there have been studies that used twin
siblings to answer this kind of question. Of course they are very limited, as
you can imagine.

Finally, the next best thing, is to see what happened to patients similar to the
patient in question. This is the idea in clinical trials, where patients are
randomly given treatment A or treatment B, with the hope that if we do this for
a large enough number of people, then patients receiving treatment A will be on
average similar to patients receiving treatment B. For example, the average age
will be similar between two groups, the percentage of female patients will be
also similar, and so on. Then you can compare what happened on average to all
the people receiving treatment A, see what happened on average to patients
receiving treatment B and decide that, on average, say treatment A is better.

But, what about the original patient for whom we needed to make the decision?
One approach would be to say, that since on average treatment A is better, give
the patient treatment A. But can we expect that these treatments work the same
for all people? Should we maybe expect that for some people, treatment B might
work better or maybe for some people both treatments work equally well?

That is actually often anticipated and we often use the term treatment effect
heterogeneity to describe this non-random variability of patients' responses to
treatment. That's why even when researchers design clinical trials, they take
into account that they should look into more specific groups of people. For
example, in addition to the average effect, they also compare the treatment
effects between males and females. Or older and younger patients.

But how do you come up with these groups? When you decide to compare the two
treatments in male and female patients, you silently assume that male patients
are similar enough to have the same response to treatment. So are female
patients. But is that enough? Maybe being a diabetic is also important in
addition to being male or female. But maybe even that is not enough
either. Maybe age is also important. So you see that we have another problem in
our hands.

\newpage

# Slide 8

What makes two patients similar? More specifically, what makes two patients
similiar for us to assume that their response to the treatments in question will
be the same? For any two patients we can always find many characteristics that
make them similar and many more that make them different. How do we proceed, in
a more standardized manner, to identify such characteristics and ultimately
answer our question: What is the predicted benefit for a specific patient if I
give them treatment A compared to treatment B? How much will treatment A reduce
a specific patient's likelihood of having a bad outcome, like a heart attack
from the example earlier, compared to treatment B?

As the first aim of this thesis, it made sense to search the literature for
existing methods for the prediction of benefit and divide them into categories
based on how they defined patient similarity.

\newpage

# Slide 10

**TODO:** Make slide only about risk-based methods\

We identified two large groups of methods.

Risk-based methods define similarity based solely on risk factors. Going back to
the hypertension example, this would mean that these methods assume that
patients at the same risk for heart attack are expected to
experience the same effect from a treatment targeted to their disease.

<!--
Treatment effect modeling methods define similarity on risk factors and, so
called, effect modifiers. Effect modifiers are certain patient characteristics
that are capable of altering how effective a treatment will be for a
patient. So, it seems that this group of methods may make a lot of sense to
focus on since, they not only require patients to be at the same risk for the
outcome we are trying to prevent but also require them to interact with
treatment in the same way. There is, however, an important problem. These
characteristics are not always known or they can be so many making very hard to
for us to put in a model.

Therefore, as the subtitle of this thesis says, we will focus on risk-based
methods.
-->

\newpage

# Slide 11

And this brings us to the second aim of my thesis: Develop scalable risk-based
approaches to the assessment of treatment effect heterogeneity.

But, first, a short introduction is required. For the entirety of my PhD we were
very lucky to have access to data of millions of patients, mainly from the US
and Europe for our experiments. This data did not come from clinical trials, but
rather, it was data collected from patients interacting with the healthcare
system. For example we had access to data that health insurance companies
collect for their insured patients, or that hospitals collect from patients they
treat. We often call this information real-world data as opposed to data from
clinical trials, where the setting is very tightly controlled.

This is both a blessing, and a curse. It's a blessing because we can analyze
data of millions of people. This allows us to explore relationships between
treatments and patient characteristics in often a lot more depth, compared to
what we could do with clinical trials, where sample sizes are often limited.

However, there are also several issues that arise from this type of
data. Randomization which was key for easily achieving patient similarity is now
gone. Since this is "real world data", it means that we get to see patients
treated by physicians that, have reason to believe that using treatment A on a
certain patient will be better for them compared to treatment B. Hopefully, they
don't simply rely on the flip of a coin to make that suggestion.

\newpage

# Slide 12

Howerver, for us, this creates the problem. Patients receiving different
treatments tend to be systematically different. This makes comparisons a lot
more challenging. But not impossible. Not always, anyway. There are methods that
we can use to make patients receiving different treatments more similar and thus
achieve a setup closer to a clinical trial that used randomization.

\newpage

# Slide 13

And that is not all. Our aim was to develop scalable methods, that is develop
methods that can be applied across different databases.

However there is, unfortunately another problem with this type of data. That is,
the lack of interoperability between observational databases. In simple words,
each database of this kind, tends to use its own way of storing patient data,
and, therefore, if I want to use multiple of these databases, I will need to
redesign my analysis every time, to be able to speak at its of the databases I
have access to.

Luckily, we were able to avoid this problem by using what is the OMOP common
data model. Without going into much detail, we can think of a common data model
similar to what is happening in this room at this moment. There are many of us
speaking different languages, however you can all understand what I am
saying. Hopefully. The common data model sits on top of all our databases and
acts as sort of a translator. We only need to speak to it and it will take care
of the rest.

This is very important. Now I can use the same design and apply it in the
Netherlands, the US, S. Korea and so on. This allows my methods to become
scalable.

\newpage

# Slide 14

Now, since we have resolved the previous problems, we can proceed with the
definition of a standardized framework for risk-based evaluation of treatment
effect heterogeneity. That is, come up with a clearly defined approach to
describe how differences between two or more treatments change with increasing
risk for a specific outcome of interest. For example, say that treatment A works
better than treatment B in patients at high risk for heart attack, but for low
risk patients, both treatments work equally well.

This framework consists of five steps. In the first step, we come up with
definitions of what is treatment A, what is treatment B, what is the outcome of
interest? For example, what do I need to see in the data to say that a specific
patient had an heart attack? However, I have to make sure that my
definitions are created in such a way, so that they can be understood from the
OMOP common data model, our translator.

Then, I can send them to databases using the common data model and extract the
patients I need.

Once I have my data, I can proceed with developing models for the prediction of
the outcome of interest. Let's say in this example I am interested to see how
treatment A and treatment B compare for the prevention of heart attack. So I
develop models for the prediction of heart attack risk.

Once I have these prediction models, I can split my patients into groups of
predicted risk, from lower to higher. For example, in the first group I have
patients with below 1% chance of having a heart attack, in the second
group I have patients between 1% and 1.5% risk and so on.

Then, I can go into each of these groups and compare treatment A to treatment B
and see how well they perform.

In the final step, I can combine all the results from the different databases,
to get a better view of how these treatments compare.

\newpage

# Slide 15

Because all these may sound a bit abstract I have included the results of one of
our studies, presented in chapter 3 of my thesis. In this case I am comparing
two treatments, thiazide diuretics and angiotensin converting enzyme inhibitors
for the treatment of hypertension.

Without going into much detail, let's focus on the picture on the left. On the
horizontal axis we show heart attack risk. So, as we move from the left to the
right we see what happens to patients with higher chances of having a heart
attack. On the vertical axis we have the absolute risk reduction, or in more
simple terms, how much better are thiazide diuretics compared to angiotensin
converting enzyme inhibitors. So, the more we move upwards, the better thiazide
diuretics are for the prevention of a heart attack. Now each color on the plot
represents a different database we ran our analysis.

The important thing to see here is that as we go from the left to right the
points tend to move upwards. As risk of heart attack increases,
thiazide diuretics tend to do better than angiotensin converting enzyme
inhibitors.

In the second picture, we see a similar trend but not as clear as before. This
is how our two treatments compare for the prevention of requiring
hospitalization with heart failure.

Finally, in the last picture we have stroke. Here we see that the two treatments
are almost the same.


\newpage

# Slide 16

Now, even though the previous method shows us how two treatments compare in
patients with different risks, it does not directly provide us with an answer to
our original question. For a specific patient, which of the two treatments is
better? Or, to make it a bit more specific, for a patient with a specific risk
prediction, which of the two treatments is better?

In the previous approach, we were still dealing with patient groups. Our
specific patient, based on their predicted risk, would fall into one of the risk
groups we defined and, then, our decision would be based on how the two
treatments performed ON AVERAGE in patients of similar, BUT NOT THE SAME risk.

So, we went ahead, and looked into simple methods to do exactly that. For each
patient with a specific risk prediction, provide them with a prediction of how
much their risk will be reduced if they go for treatment A compared to treatment
B.

I will not go into depth about the methods we considered, as this could take
some time. However, I will show you this figure from chapter 4, to get an idea
what our results would look like.

So in this case, we again have risk on the horizontal axis and predicted benefit
on the vertical axis. Each line represents one of the several methods we
compared. So for a patient at specific risk, you could use one of these lines to
derive how much your risk would be reduced if you opted for treatment A compared
to treatment B.

This is a short description of the contents of my thesis. How I developed
increasingly personalized approaches that could be used to aid doctors and
patients with their decisions.

\newpage

# Slide 17

And with that I would like to thank you all for your attention and give the word
back to rector magnificus.
